apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: skymap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: skymap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: root-password
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-name
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: skymap
spec:
  selector:
    app: db
  ports:
    - port: 3306
