apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: skymap
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: sky_map-init-db:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-name
      restartPolicy: OnFailure
