# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: skymap
type: Opaque
stringData:
  # Utilisation de stringData permet de ne pas avoir à encoder en base64 manuellement ici
  root-password: "changeme"
  db-user: "sky"
  db-password: "changeme"
  db-name: "sky_map"
